### NumPy with Mycticount X

Saya membuat ini atas refrensi dari Buku **"Python Machine Learning Cookbook"** by **Chris Albon**.
Bukunya sangat rekomen buat kalian yang pemula Machine Learning dan Data Scientist

In [ ]:
import numpy as np

## 1. Vector and Array

In [ ]:
row_vector = np.array([1, 2, 3])
row_vector

array([1, 2, 3])

In [ ]:
col_vector = np.array([[1],
                  [2],
                  [3]])
col_vector

array([[1],
       [2],
       [3]])

## 2. Matrix

In [ ]:
# Standard Matrix
mtx = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Inverse Matrix
mtx = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

try :
  mtx_inv = np.linalg.inv(mtx)
  mtx_inv
except :
  print("Singular Matrix")
  print("Determinant : ", np.linalg.det(mtx))

Singular Matrix
Determinant :  0.0


In [ ]:
# Btw NumPy punya function tersendiri buat Matrix
mtx = np.matrix([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

mtx


matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## 3. Sparse Matrix

Sparse Matrix dalam Python adalah matriks yang sebagian besar elemennya bernilai nol atau kosong, sehingga penyimpanan dan operasinya lebih efisien menggunakan struktur data khusus. Alih-alih menyimpan semua elemen dalam array 2D biasa, sparse matrix hanya menyimpan elemen yang bukan nol beserta indeksnya.

In [ ]:
# Sparse Matrix
from scipy import sparse

dense_matrix = np.array([
    [0, 0, 3],
    [4, 0, 0],
    [0, 5, 0]
])

sparse_matrix = sparse.csr_matrix(dense_matrix)
print(sparse_matrix)


  (0, 2)	3
  (1, 0)	4
  (2, 1)	5


Elemen 3 berada di baris 0, kolom 2 → (0, 2) 3

Elemen 4 berada di baris 1, kolom 0 → (1, 0) 4

Elemen 5 berada di baris 2, kolom 1 → (2, 1) 5

## 4. Element

In [ ]:
# Selecting Element
vtr = np.array([1, 2, 3, 4, 5])
mtx = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Python Slicing Techinique: Vector Form
print(vtr[:])
print(vtr[1:3])
print(vtr[1:])
print(vtr[:-1])
print(vtr[::2])

# Pengguna C terdiam melihat ini:
print(vtr[::-1])


[1 2 3 4 5]
[2 3]
[2 3 4 5]
[1 2 3 4]
[1 3 5]
[5 4 3 2 1]


## 5. STS: Shape, Size, Dimension

In [ ]:
# Sekedar Tahu Saja: Shape, Size, dan Dimension

mtx = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Shape: Mengembalikan tuple: dimensi
print("Shape:", mtx.shape) # Output: (3, 3) -> 3 baris, 3 kolom

# Size: Mengembalikan int: total elemen
print("Size:", mtx.size)  # Output: 9 -> total 9 elemen

# ndim: Mengembalikan int: jumlah dimensi
print("Dimension:", mtx.ndim)  # Output: 2 -> matriks 2 dimensi (baris dan kolom)



Shape: (3, 3)
Size: 9
Dimension: 2


In [ ]:
vtr = np.array([1, 2, 3, 4, 5])

# Shape: Mengembalikan tuple yang menunjukkan dimensi vektor
print("Shape:", vtr.shape)  # Output: (5,) -> vektor 1 dimensi dengan 5 elemen

# Size: Mengembalikan jumlah total elemen dalam vektor
print("Size:", vtr.size)  # Output: 5 -> total 5 elemen

# ndim: Mengembalikan jumlah dimensi vektor
print("Dimension:", vtr.ndim)  # Output: 1 -> vektor 1 dimensi


Shape: (5,)
Size: 5
Dimension: 1


## 6. Operasi

In [ ]:
# Operasi NumPy
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

matrix = matrix + 100
print(matrix)

[[101 102 103]
 [104 105 106]
 [107 108 109]]


In [ ]:
# Ini namanya gabutz
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Baca: Fungsi Lambda menerima i : mengembalikan i + 100
adder = lambda i : i + 100

# Baca: Lancarkan fungsi add untuk setiap index matrix
matrix = np.vectorize(adder)(matrix)

print(matrix)

[[101 102 103]
 [104 105 106]
 [107 108 109]]


In [ ]:
# Max und Min
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print("Max:", np.max(matrix))
print("Min:", np.min(matrix))

Max: 9
Min: 1


In [49]:
# Matrix Dot Product
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(f"Dot Product:\n", np.dot(matrix, matrix))
print(matrix @ matrix)

Dot Product:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [50]:
# Matrix Cross Product
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(f"Cross Product:\n",np.cross(matrix, matrix))

Cross Product:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [52]:
# Matrix Operation
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(matrix + matrix)
print(matrix - matrix)
print(matrix * matrix) # Element Wise
print(matrix / matrix)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## 7. Basic Statistic

In [ ]:
# Average / Mean
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print("Average:", np.mean(matrix))

Average: 5.0


In [ ]:
# Variance
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print("Variance:", np.var(matrix))


Variance: 6.666666666666667


In [ ]:
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print("Standard Deviation:", np.std(matrix))


Standard Deviation: 2.581988897471611


## 8. Matrix Signature

In [26]:
# Matrix Reshape
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                   [10, 11, 12]])

print(matrix.reshape(2, 6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [30]:
# Reshaper -1 "As Many As Needed"
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                   [10, 11, 12]])

print(matrix.reshape(2, -1))
print(matrix.reshape(-1, 3))

# Reshaper single int
print(matrix.reshape(12))

# Tidak Bisa: print(matrix.reshape(10))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [31]:
# Matrix Transpose
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(matrix.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [32]:
# Ada hal unik ketika kalian transpos Vektor

# Tipe 1
vektor = np.array([1, 2, 3, 4, 5, 6])
print(vektor.T) # NumPy menganggap ini benda 1D gaboleh ditranspose / ditranspose ujungnya sama aja

# Tipe 2
vektor_col = np.array([[1, 2, 3, 4, 5, 6]])
print(vektor_col.T)


[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [34]:
# Flattening Matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(matrix.flatten())

# or
print(matrix.reshape(1, -1))

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5 6 7 8 9]]


## 9. Linear Algebra

Ada modul dalam NumPy bernama linalg, bisa dipake buat "nyontek" jawaban Linear Algebra bagian Matrix dan Vektor

Rank itu dipake buat ngecek apakah sistem persamaan linear itu **memiliki solusi yang unik** (Ga punya Infinite Solution). Rank ngecek **berapa banyak baris yang unik**

2 4 6

1 2 3

3 6 9

Ini tidak unik, rank = 1 karena
- Row1 = 2 x Row2
- Row3 = 3 x Row1

In [39]:
# Rank of Matrix
matrix = np.array([[1, 2, 3],
                  [2, 4, 6],
                  [3, 6, 9]])

print("Rank: ", np.linalg.matrix_rank(matrix))

matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print("Rank: ", np.linalg.matrix_rank(matrix))

Rank:  1
Rank:  2


In [40]:
# Determinan Matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print("Determinant: ", np.linalg.det(matrix))

Determinant:  0.0


In [ ]:
# Determinan
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print("Diagonal: ", matrix.diagonal())

In [ ]:
# Trace
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print("Trace: ", matrix.trace())

In [42]:
# Eigen Value and Eigen Vector
matrix = np.array([[2, 0, 0, 0],
                  [1, 4, 0, 1],
                  [3, 1, 5, 2],
                  [0, 0, 0, 1]])

eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues: ", eigenvalues)
print("Eigenvectors: ", eigenvectors)

Eigenvalues:  [5. 4. 2. 1.]
Eigenvectors:  [[ 0.          0.          0.71713717  0.        ]
 [ 0.          0.70710678 -0.35856858 -0.29408585]
 [ 1.         -0.70710678 -0.5976143  -0.36760731]
 [ 0.          0.          0.          0.88225755]]


In [ ]:
# Matrix Inversion
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print("Inverse: ", np.linalg.inv(matrix))

## 10. Random Matrix Generator

In [53]:
np.random.seed(0) # Set seed, Satu Seed bakalan sama terus outputnya
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

**Format: (From, To, Size)**

In [54]:
# Random Int
np.random.randint(0, 11, 3)

array([3, 7, 9])

In [55]:
# Random Normal
np.random.normal(0, 1, 3)

array([-1.42232584,  1.52006949, -0.29139398])

In [57]:
# Random Logistic
# Format: (Loc / Mean, Scale, Size)
np.random.logistic(0, 1, 3)


array([-0.08013416, -0.4356214 ,  1.62933678])

In [58]:
# Random Uniform
# Tipe Random tapi ga boleh sama dengan si Parameter pengapitnya
np.random.uniform(0, 1, 3)

array([0.33739616, 0.64817187, 0.36824154])